language: java
install: true
jdk: oraclejdk8
dist: trusty
sudo: true

before_install:
  - chmod +x mvnw

stages:
  - compile
  - test

cache:
  directories:
    - .autoconf
    - $HOME/.m2

spring:
  datasource:
    url: ${jdbc:mysql://localhost:3306/account_manager?useSSL=false&serverTimezone=UTC}
    username: ${user}
    password: ${password}